[project]
name = "odoo-addons-sygel-technology-sy-stock-logistics-workflow"
version = "18.0.20260529.0"
dependencies = [
    "odoo-addon-stock_picking_force_availability==18.0.*",
    "odoo-addon-stock_picking_report_line_product_without_internal_ref==18.0.*",
    "odoo-addon-stock_picking_very_high_priority==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
